Disable precommit static checks.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,26 +17,26 @@ env:
 jobs:
 
 
-  static-checks:
-    name: '📊 Static checks'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@f1d3225b5376a0791fdee5a0e8eac5289355e43a  # pin@v2
-        with:
-            submodules: true
-      - name: Set up Python
-        uses: actions/setup-python@0291cefc54fa79cd1986aee8fa5ecb89ad4defea  # pin@v2
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-      - name: Bootstrap
-        run: |
-          set -eux
-          python --version
-          pip install pre-commit
-      - name: Pre-commit hooks check
-        run: |
-          pre-commit run --all-files --show-diff-on-failure
+  #  static-checks:
+  #  name: '📊 Static checks'
+  #  runs-on: ubuntu-latest
+  #  steps:
+  #    - name: Checkout
+  #      uses: actions/checkout@f1d3225b5376a0791fdee5a0e8eac5289355e43a  # pin@v2
+  #      with:
+  #          submodules: true
+  #    - name: Set up Python
+  #      uses: actions/setup-python@0291cefc54fa79cd1986aee8fa5ecb89ad4defea  # pin@v2
+  #      with:
+  #        python-version: ${{ env.PYTHON_VERSION }}
+  #    - name: Bootstrap
+  #      run: |
+  #        set -eux
+  #        python --version
+  #        pip install pre-commit
+  #    - name: Pre-commit hooks check
+  #      run: |
+  #        pre-commit run --all-files --show-diff-on-failure
 
 
 #################################################################################
